### ISSUE TITLE
Notice: Use of undefined constant AF_INET - assumed 'AF_INET' 

### ISSUE THREAD

**Issue by dpkcse** [uri2x/php-cassandra#3]
Notice: Use of undefined constant AF_INET - assumed 'AF_INET' in  \Cassandra\Cassandra.php on line 151

How to solve this warning.

**Comment by uri2x** [comment]
Make sure you install the PHP Sockets extension. It is available for every PHP release. If you're using Windows then edit your php.ini file and uncomment the line that says 

> extension=php_sockets.dll

**Comment by dpkcse** [comment]
Thanks, got it.
